# Settings for the app
app:
  # HTML Title
  title: Georgia Tires
  # Header name
  name: GA Tires
  # Meta description that will show up in Google search results
  meta_description: _(Georgia Tires is a tool for residents to report illegally dumped or abandoned tires)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: 33.7489
      lng: -84.3881
    zoom: 12
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  tire:
    default: gray
    focused: red
    label: _(Tire)

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  tire:
    default: gray
    focused: red
    label: _(Tire)
  park:
    default: gray
    focused: red
    label: _(Park)
  school:
    default: gray
    focused: red
    label: _(School)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  gray:
    iconUrl: /static/css/images/dot-rr-color.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: false
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Report a tire)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    # - prompt: _(Location Name)
    #   type: text
    #   name: name
    #   attrs:
    #     - key: placeholder
    #       value: _(Location Name)
    #     - key: size
    #       value: 30

    - type: hidden
      name: location_type
      attrs:
        - key: value
          value: tire

      name: location_type
    - prompt: _(Number of Tires)
      label: 'Number of tires:'
      type: number
      attrs:
        -key: min
        -value: 1
      name: number_tires
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name (public))
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)

# survey:
#   submission_type: comments

#   # Response config
#   show_responses: true
#   response_name: _(comment)
#   response_plural_name: _(comments)
#   action_text: _(commented on)
#   anonymous_name: _(Someone)

#   # Survey form config
#   title: _(Leave a Comment)
#   form_link_text: _(Leave a Comment)
#   submit_btn_text: _(Comment)
#   items:
#     - prompt: _(Comment)
#       label: _(Comment)
#       type: textarea
#       name: comment
#     - prompt: _(Your Name)
#       type: text
#       name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: about
    #start_page: true
  - title: Download the Data!
    external: true
    url: /download/places.csv
